FROM nldi-db_nldi_db

MAINTAINER David Steinich <drsteini@usgs.gov>

############################################
# Grab Files to Load the Demo Database Data
############################################

COPY ./3_run_liquibase_ci.sh /docker-entrypoint-initdb.d/
