version: '3.3'
services:

  ci:
    image: nldi-db-ci
    build:
      context: .
      dockerfile: ./database/ci/Dockerfile
    networks:
      nldi:
        ipv4_address: ${DB_CI_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${NLDI_DATABASE_NAME}
      - NLDI_DATABASE_NAME=${NLDI_DATABASE_NAME}
      - NLDI_DB_OWNER_USERNAME=${NLDI_DB_OWNER_USERNAME}
      - NLDI_DB_OWNER_PASSWORD=${NLDI_DB_OWNER_PASSWORD}
      - NLDI_SCHEMA_OWNER_USERNAME=${NLDI_SCHEMA_OWNER_USERNAME}
      - NLDI_SCHEMA_OWNER_PASSWORD=${NLDI_SCHEMA_OWNER_PASSWORD}
      - NHDPLUS_SCHEMA_OWNER_USERNAME=${NHDPLUS_SCHEMA_OWNER_USERNAME}
      - NLDI_READ_ONLY_USERNAME=${NLDI_READ_ONLY_USERNAME}
      - NLDI_READ_ONLY_PASSWORD=${NLDI_READ_ONLY_PASSWORD}
      - NLDI_DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_CI_PORT}:5432
    container_name: nldi-db-ci

  demo:
    image: nldi-db-demo
    build:
      context: .
      dockerfile: ./database/demo/Dockerfile
    networks:
      nldi:
        ipv4_address: ${DB_DEMO_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${NLDI_DATABASE_NAME}
      - NLDI_DATABASE_NAME=${NLDI_DATABASE_NAME}
      - NLDI_DB_OWNER_USERNAME=${NLDI_DB_OWNER_USERNAME}
      - NLDI_DB_OWNER_PASSWORD=${NLDI_DB_OWNER_PASSWORD}
      - NLDI_SCHEMA_OWNER_USERNAME=${NLDI_SCHEMA_OWNER_USERNAME}
      - NLDI_SCHEMA_OWNER_PASSWORD=${NLDI_SCHEMA_OWNER_PASSWORD}
      - NHDPLUS_SCHEMA_OWNER_USERNAME=${NHDPLUS_SCHEMA_OWNER_USERNAME}
      - NLDI_READ_ONLY_USERNAME=${NLDI_READ_ONLY_USERNAME}
      - NLDI_READ_ONLY_PASSWORD=${NLDI_READ_ONLY_PASSWORD}
      - NLDI_DATABASE_ADDRESS=127.0.0.1
    ports:
      - ${DB_DEMO_PORT}:5432
    container_name: nldi-db-demo

  db:
    image: postgis/postgis:12-3.0
    networks:
      nldi:
        ipv4_address: ${DB_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${NLDI_DATABASE_NAME}
    ports:
      - ${DB_PORT}:5432
    container_name: nldi-db

  liquibase:
    image: nldi-liquibase
    depends_on:
      - db
    build:
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
        - A_JDBC_JAR=${JDBC_JAR}
    networks:
      nldi:
        ipv4_address: ${LIQUIBASE_IPV4}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${NLDI_DATABASE_NAME}
      - NLDI_DATABASE_NAME=${NLDI_DATABASE_NAME}
      - NLDI_DB_OWNER_USERNAME=${NLDI_DB_OWNER_USERNAME}
      - NLDI_DB_OWNER_PASSWORD=${NLDI_DB_OWNER_PASSWORD}
      - NLDI_SCHEMA_OWNER_USERNAME=${NLDI_SCHEMA_OWNER_USERNAME}
      - NLDI_SCHEMA_OWNER_PASSWORD=${NLDI_SCHEMA_OWNER_PASSWORD}
      - NHDPLUS_SCHEMA_OWNER_USERNAME=${NHDPLUS_SCHEMA_OWNER_USERNAME}
      - NLDI_READ_ONLY_USERNAME=${NLDI_READ_ONLY_USERNAME}
      - NLDI_READ_ONLY_PASSWORD=${NLDI_READ_ONLY_PASSWORD}
      - NLDI_DATABASE_ADDRESS=${NLDI_DATABASE_ADDRESS}
    volumes:
      - ./liquibase/changeLogs:/home/java/workspace/
      - ./liquibase/scripts/dbInit:/docker-entrypoint-initdb.d
    container_name: nldi-liquibase

networks:
  nldi:
    external:
      name: ${LOCAL_NETWORK_NAME}
