#!/bin/bash

echo Building base container...
docker build -f Dockerfile.base -t base .
docker push base

echo Building target container...
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME-$SOURCE_COMMIT .
